### ISSUE TITLE
additional meta attributes in go-import and go-source metatags on solace.dev/go/messaging

### ISSUE THREAD

**Issue by Shegox** [SolaceProducts/pubsubplus-go-client#9] opened 2023-02-15 08:11 UTC
Hi team, 

we're very happy users of the `solace.dev/go/messaging` library. In order to keep our dependencies up-to-date we leverage 
[Renovate](https://github.com/renovatebot/renovate) and now noticed that Renovate isn't able to properly detect the source (aka this repository) to check for new releases. 

For Renovate (and the golang cli) to determine the source, the page `solace.dev/go/messaging?go-get=1` contains these import meta HTML tags: 
```html
<meta data-react-helmet="true" name="go-import" content="solace.dev/go/messaging git https://github.com/SolaceProducts/pubsubplus-go-client"/>

<meta data-react-helmet="true" name="go-source" content="solace.dev/go/messaging https://github.com/SolaceProducts/pubsubplus-go-client https://github.com/SolaceProducts/pubsubplus-go-client/tree/master{/dir} https://github.com/SolaceProducts/pubsubplus-go-client/tree/master{/dir}/{file}#L{line}"/>
```

The golang client is able to parse them, but Renovate runs into problems as it uses [a very simplistic Regex matcher](https://github.com/renovatebot/renovate/blob/d869c946d164965393f1259db5171e2a0303fb27/lib/modules/datasource/go/base.ts#L82-L84) to extract the pattern and the additional `data-react-helmet="true"` causes it to stumble and fail. I'm aware that this can (and probably should) be overcome in Renovate directly with adding a more robust XML-parser, but that is probably a bigger undertaking. 

I now wanted to reach out and ask if it would be please possible to remove the `data-react-helmet="true"` from the import page. Allowing Renovate to recognize the source location and propose updates. I assume these html attributes are auto-injected by React during your website build process. There seems to be some options to disable/remove them: https://github.com/nfl/react-helmet/issues/79

Already many thanks for taking this into account. :)

**Comment by TamimiGitHub** [comment] 2023-02-16 21:39
Hey @Shegox - thanks for the detailed explanation on what the issue is! Looking into it, I was able to find a workaround to add the necessary meta headers without having the `data-react-helmet="true"` tag. The fix is pushed, please test from your end and let me know if it resolves your issue. 

Will be closing this issue for now

**Closed** 2023-02-16 21:40 UTC

**Comment by Shegox** [comment] 2023-02-17 02:46
Hi @TamimiGitHub, 

thanks for looking into and pushing a fix. I just tested it and it seems that the tags are now completely gone:
```bash
$ curl -L 'solace.dev/go/messaging?go-get=1' | grep 'go-import'
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    55  100    55    0     0   1083      0 --:--:-- --:--:-- --:--:--  1341
100    59  100    59    0     0    528      0 --:--:-- --:--:-- --:--:--   528
100  5863  100  5863    0     0  31333      0 --:--:-- --:--:-- --:--:-- 31333
100  5863  100  5863    0     0  27597      0 --:--:-- --:--:-- --:--:-- 27597
```

A normal `go get` fails now as well: 
```bash
$ export GOPROXY=direct

$ go get solace.dev/go/messaging
go: unrecognized import path "solace.dev/go/messaging": parse https://solace.dev/go/messaging?go-get=1: no go-import meta tags ()
```
